
services:
  backend:
    container_name: backend
    build: ./backend
    env_file:
     - ./backend/.env
    networks:
      - net-rotaexpress
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./frontend/public:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - net-rotaexpress

networks:
  net-rotaexpress:
    external: true 