
services:
  backend:
    container_name: backend
    build: ./backend
    env_file:
     - ./backend/.env
    networks:
      - net-rotaexpress
    command: node index.js
  
  test:
    container_name: backend-test
    build: ./backend
    env_file:
     - ./backend/tests/.env.test
    networks:
      - net-rotaexpress
    profiles:
      - test
    command: npm run test  

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/public:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - net-rotaexpress

networks:
  net-rotaexpress:
    external: true 